## Load in Numpy

In [1]:
import numpy as np
import sys

In [2]:
a = np.array([1, 2 ,3], dtype ='int64')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


#### Dimension: .ndim

In [4]:
b.ndim 

2

#### Get Shape: .shape


In [5]:
b.shape


(2, 3)

#### Get Type: .dtype


In [6]:
a.dtype

dtype('int64')

#### Get Size

In [7]:
b.itemsize

8

#### Get Total Size

In [8]:
a.size

3

#### Get total size

In [9]:
a.nbytes

24

## Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[0, 0]

1

In [12]:
# Get a specific row [r, :]
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [13]:
# Ge a specific column [:, c]
a[:, 5]

array([ 6, 13])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,1] = 8
print(a)
a[:, 1] = 9
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  8 10 11 12 13 14]]
[[ 1  9  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### 3D example:


In [16]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specififc element (work outside in)
b[0,1,1]

4

In [18]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [19]:
b[:, 1, :] = [[9,9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays


In [20]:
# All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# all 1s matrix
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
# Any other number
np.full((2,2,2), 99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [23]:
# Any other number (full_like)
print(a)
np.full_like(a, 4)  # or np.full(a.shape, 4)

[[ 1  9  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random decimal numbers
c = np.random.rand(4,2, 3)  # [r, c, h]
# random decimal number between 0 and 1
c

array([[[0.86081179, 0.61996802, 0.58023894],
        [0.14963076, 0.33850638, 0.50605382]],

       [[0.28784786, 0.68159917, 0.65871027],
        [0.537031  , 0.82950153, 0.94131523]],

       [[0.9574117 , 0.26870652, 0.44730171],
        [0.11657903, 0.7779171 , 0.49637514]],

       [[0.23768957, 0.53800016, 0.30127089],
        [0.16995738, 0.35480218, 0.9459468 ]]])

In [25]:
c = np.random.random_sample(a.shape)  # like shape of a
c

array([[0.95711975, 0.2939098 , 0.26546997, 0.12660001, 0.71386194,
        0.86789621, 0.78505196],
       [0.23310211, 0.32835753, 0.23512709, 0.77802484, 0.24153574,
        0.56893448, 0.3756964 ]])

In [26]:
# Random Integer values
np.random.randint(-100, 100, size = a.shape)

array([[ -95,  -21,   17,  -25,   11,  -36, -100],
       [ -39,   96,  -66,   91,  -19,   50,  -22]])

In [27]:
# The identity matrix (square)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
 # Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Challenges:


In [29]:
output = np.ones((5,5))
inner1 = np.zeros((3,3))
inner1[1,1] = 9
output[1:-1, 1:-1] = inner1
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be careful when copying arrays!!

In [30]:
a = np.array([1,2,3])
b = a.copy()       # dont a = b (this makes b point to the same location as a points)
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [31]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a + 2   # different from += 2
a

array([1, 2, 3, 4])

In [33]:
a - 2

array([-1,  0,  1,  2])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
b = np.array([1,0,1,0])
a + b


array([2, 2, 4, 4])

In [38]:
np.cos(a)   # a in radian

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [96]:
output = np.ones((6,5))
for i in range(1, 31):
    output[(i - 1)// 5, (i-1) % 5] = i
output

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

0

#### Linear Algebra


In [39]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [40]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
c = np.identity(5)
np.linalg.det(c)

1.0

In [42]:
a = np.array(([1, 2], [3, 4]))
b = np.linalg.inv(a)
print(a)
print(b)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [43]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#### Statistics

In [44]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats, axis = 0) # axis = 0 means row, axis = 1 means column

array([1, 2, 3])

In [46]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [47]:
np.sum(stats)  # axis = 0 or 1

21

### Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [49]:
after = before.reshape((1, 8))
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [50]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])  
v2 = np.array([5,6,7,8])   # cant mixmatch
np.vstack([v1,v2,v1,v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [51]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous


### Load Data from file

In [52]:
filedata = np.genfromtxt('data.txt', delimiter =',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [53]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [54]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [55]:
## You can index with a list in NumPy

In [57]:
a = np.array([1, 10, 100, 1000])
a[[1, 3]]

array([  10, 1000])

In [61]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

##### Bolean Masking and Advanced Indexing

In [67]:
~((filedata > 50) & (filedata < 100))


array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])